@Library('jenkins-pipeline-utils') _

node('integration'){
  properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')),
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    parameters([
      string(defaultValue: 'latest', description: 'Container version', name: 'APP_VERSION'),
      string(defaultValue: 'inventories/integration/hosts.yml', description: 'Ansible inventory', name: 'INVENTORY'),
      string(defaultValue: 'deploy-intake.yml', description: 'Ansible playbook', name: 'PLAYBOOK_NAME'),
      booleanParam(defaultValue: true, description: 'Enable/Disable New Relic agent', name: 'ENABLE_NEWRELIC')]),pipelineTriggers([])
  ])

  stage('Get necessary artifacts'){
    git branch: 'master', credentialsId: 'fa29964d-237e-4ecb-96bc-1350dda63f79', url: 'git@github.com:ca-cwds/devops.git'
    dir('de-ansible'){
      git branch: 'master', credentialsId: 'fa29964d-237e-4ecb-96bc-1350dda63f79', url: 'git@github.com:ca-cwds/de-ansible.git'
    }
  }

  stage('Deploy to Integraton'){
    dir('de-ansible'){
      sh "ansible-playbook -e NEW_RELIC_AGENT=$ENABLE_NEWRELIC -e INTAKE_APP_VERSION=$APP_VERSION -i $INVENTORY $PLAYBOOK_NAME --vault-password-file ~/.ssh/vault.txt -vv"
    }
  }

   stage('Update manifest'){
    updateManifest("intake", "integration", "fa29964d-237e-4ecb-96bc-1350dda63f79", env.APP_VERSION)
  }

  stage('Clean'){
    cleanWs()
  }
}
